---
- hosts: all
  roles:
    - role: ansible-role-omero-logmonitor
      omero_logmonitor_slack_name: molecule-test
      omero_logmonitor_slack_token: DUMMY_TOKEN
      omero_logmonitor_slack_channel: "#molecule-test"
